import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/Header';
import React from "react";

export default function Home() {
    return (
        <React.Fragment>
            <Head>
                <title>Ton</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/ton_symbol.png"/>
            </Head>
            <Header/>
            <main className={styles.main}>
            </main>
        </React.Fragment>
    )
}
